// This source file is generated by Oracle tools and is subject to change
// It is a utility client for invoking the operations of the Web service port.
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.services.ws.proxy;

import oracle.webservices.transport.ClientTransport;
import oracle.webservices.OracleStub;
import javax.xml.rpc.ServiceFactory;
import javax.xml.rpc.Stub;

public class __soap_EnvioNominas_RS_envioNominasPortClient {
    private cl.bicevida.envionominas.model.services.ws.proxy.EnvioNominasPort _port;
    
    public __soap_EnvioNominas_RS_envioNominasPortClient() throws Exception {
        ServiceFactory factory = ServiceFactory.newInstance();
        _port = ((cl.bicevida.envionominas.model.services.ws.proxy.EnvioNominasPortService)factory.loadService(cl.bicevida.envionominas.model.services.ws.proxy.EnvioNominasPortService.class)).get__soap_EnvioNominas_RS_envioNominasPort();
    }
    
    /**
     * @param args
     */
    public static void main(String[] args) {
        try {
            cl.bicevida.envionominas.model.services.ws.proxy.__soap_EnvioNominas_RS_envioNominasPortClient myPort = new cl.bicevida.envionominas.model.services.ws.proxy.__soap_EnvioNominas_RS_envioNominasPortClient();
            System.out.println("calling " + myPort.getEndpoint());
            // Add your own code here
        
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * delegate all operations to the underlying implementation class.
     */
    
    public cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CargaNominaOutputType cargar(cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CargaNominaInputType cargaNominaInput) throws java.rmi.RemoteException, cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.ErrorType {
        return _port.cargar(cargaNominaInput);
    }
    
    public cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RindeNominaOutputType rendir(cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RindeNominaInputType rindeNominaInput) throws java.rmi.RemoteException, cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.ErrorType {
        return _port.rendir(rindeNominaInput);
    }
    
    public void generarArchivo(cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CargaNominaInputType cargaNominaInput) throws java.rmi.RemoteException {
        _port.generarArchivo(cargaNominaInput);
    }
    
    
    /**
     * used to access the JAX-RPC level APIs
     * returns the interface of the port instance
     */
    public cl.bicevida.envionominas.model.services.ws.proxy.EnvioNominasPort getPort() {
        return _port;
    }
    
    public String getEndpoint() {
        return (String) ((Stub) _port)._getProperty(Stub.ENDPOINT_ADDRESS_PROPERTY);
    }
    
    public void setEndpoint(String endpoint) {
        ((Stub) _port)._setProperty(Stub.ENDPOINT_ADDRESS_PROPERTY, endpoint);
    }
    
    public String getPassword() {
        return (String) ((Stub) _port)._getProperty(Stub.PASSWORD_PROPERTY);
    }
    
    public void setPassword(String password) {
        ((Stub) _port)._setProperty(Stub.PASSWORD_PROPERTY, password);
    }
    
    public String getUsername() {
        return (String) ((Stub) _port)._getProperty(Stub.USERNAME_PROPERTY);
    }
    
    public void setUsername(String username) {
        ((Stub) _port)._setProperty(Stub.USERNAME_PROPERTY, username);
    }
    
    public void setMaintainSession(boolean maintainSession) {
        ((Stub) _port)._setProperty(Stub.SESSION_MAINTAIN_PROPERTY, Boolean.valueOf(maintainSession));
    }
    
    public boolean getMaintainSession() {
        return ((Boolean) ((Stub) _port)._getProperty(Stub.SESSION_MAINTAIN_PROPERTY)).booleanValue();
    }
    
    /**
     * returns the transport context
     */
    public ClientTransport getClientTransport() {
        return ((OracleStub) _port).getClientTransport();
    }
    
}
