// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.services.ws.proxy.runtime;

import oracle.j2ee.ws.client.BasicService;
import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.common.encoding.simpletype.*;
import oracle.j2ee.ws.common.encoding.soap.*;
import oracle.j2ee.ws.common.encoding.literal.*;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.common.soap.SOAPEncodingConstants;
import oracle.j2ee.ws.common.wsdl.document.schema.SchemaConstants;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.namespace.QName;

public class EnvioNominasPortService_SerializerRegistry extends SerializerRegistryBase implements SerializerConstants {
    public EnvioNominasPortService_SerializerRegistry() {
    }
    
    public TypeMappingRegistry getRegistry() {
        TypeMappingRegistry registry = BasicService.createStandardTypeMappingRegistry();
        TypeMapping mapping11 = registry.getTypeMapping(SOAPEncodingConstants.getSOAPEncodingConstants(SOAPVersion.SOAP_11).getURIEncoding());
        TypeMapping mapping = registry.getTypeMapping("");
        {
            QName type = new QName("http://bicevida.ws/services/envionominas", "ArchivoNominaType");
            CombinedSerializer serializer = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime.ArchivoNominaType__LiteralSerializersrc(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.ArchivoNominaType.class, type, serializer);
        }
        {
            QName type = new QName("http://bicevida.ws/services/envionominas", "ErrorType");
            CombinedSerializer serializer = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime.ErrorType__LiteralSerializersrc(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.ErrorType.class, type, serializer);
        }
        {
            QName type = new QName("http://bicevida.ws/services/envionominas", "nominas");
            CombinedSerializer serializer = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime.Nominas__LiteralSerializersrc(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.Nominas.class, type, serializer);
        }
        {
            QName type = new QName("http://bicevida.ws/services/envionominas", "DatosCabeceraType");
            CombinedSerializer serializer = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime.DatosCabeceraType__LiteralSerializersrc(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.DatosCabeceraType.class, type, serializer);
        }
        {
            QName type = new QName("http://bicevida.ws/services/envionominas", "CargaNominaOutputType");
            CombinedSerializer serializer = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime.CargaNominaOutputType__LiteralSerializersrc(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CargaNominaOutputType.class, type, serializer);
        }
        {
            QName type = new QName("http://bicevida.ws/services/envionominas", "RindeNominaOutputType");
            CombinedSerializer serializer = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime.RindeNominaOutputType__LiteralSerializersrc(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RindeNominaOutputType.class, type, serializer);
        }
        {
            QName type = new QName("http://bicevida.ws/services/envionominas", "CargaNominaInputType");
            CombinedSerializer serializer = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime.CargaNominaInputType__LiteralSerializersrc(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CargaNominaInputType.class, type, serializer);
        }
        {
            QName type = new QName("http://bicevida.ws/services/envionominas", "RindeNominaInputType");
            CombinedSerializer serializer = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime.RindeNominaInputType__LiteralSerializersrc(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RindeNominaInputType.class, type, serializer);
        }
        {
            QName type = new QName("http://bicevida.ws/services/envionominas", "NominaType");
            CombinedSerializer serializer = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime.NominaType__LiteralSerializersrc(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.NominaType.class, type, serializer);
        }
        {
            QName type = new QName("http://bicevida.ws/services/envionominas", "RegistroNominaType");
            CombinedSerializer serializer = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime.RegistroNominaType__LiteralSerializersrc(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RegistroNominaType.class, type, serializer);
        }
        {
            QName type = new QName("http://bicevida.ws/services/envionominas", "CampoVariableType");
            CombinedSerializer serializer = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime.CampoVariableType__LiteralSerializersrc(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CampoVariableType.class, type, serializer);
        }
        {
            QName type = new QName("http://bicevida.ws/services/envionominas", "camposVariables");
            CombinedSerializer serializer = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime.CamposVariables__LiteralSerializersrc(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CamposVariables.class, type, serializer);
        }
        {
            QName type = new QName("http://bicevida.ws/services/envionominas", "registrosNomina");
            CombinedSerializer serializer = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime.RegistrosNomina__LiteralSerializersrc(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RegistrosNomina.class, type, serializer);
        }
        cl.bicevida.envionominas.model.services.ws.proxy.runtime.EnvioNominasPortService_SerializerRegistry12 internal12Registry = new cl.bicevida.envionominas.model.services.ws.proxy.runtime.EnvioNominasPortService_SerializerRegistry12();
        return internal12Registry.getRegistry(registry);
    }
    
    private static void registerSerializer(TypeMapping mapping, Class javaType, QName xmlType,
        Serializer ser) {
        mapping.register(javaType, xmlType, new SingletonSerializerFactory(ser),
            new SingletonDeserializerFactory((Deserializer)ser));
    }
    
}
