// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.proxy.bdclientes.parametros;

public interface WSClientesParamFaseTres_PortType extends java.rmi.Remote {
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaAFP getListaAFP() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaActividad getListaActividad() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaCodigoArea getListaCodigosArea() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaComuna getListaComuna() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaEstadoCivil getListaEstadoCivil() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaIsapre getListaIsapre() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaLocalidad getListaLocalidad() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaNacionalidad getListaNacionalidad() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaNivelEducacional getListaNivelEducacional() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaNivelIngreso getListaNivelIngreso() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaOcupacion getListaOcupacion() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaProfesion getListaProfesion() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaRegion getListaRegion() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaSexo getListaSexo() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaTipoCalle getListaTipoCalle() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaTipoDireccion getListaTipoDireccion() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaTipoPersona getListaTipoPersona() throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaTipoVivienda getListaTipoVivienda() throws 
         java.rmi.RemoteException;
}
