// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime;

import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.common.encoding.literal.*;
import oracle.j2ee.ws.common.encoding.literal.DetailFragmentDeserializer;
import oracle.j2ee.ws.common.encoding.simpletype.*;
import oracle.j2ee.ws.common.soap.SOAPEncodingConstants;
import oracle.j2ee.ws.common.soap.SOAPEnvelopeConstants;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.common.streaming.*;
import oracle.j2ee.ws.common.wsdl.document.schema.SchemaConstants;
import oracle.j2ee.ws.common.util.xml.UUID;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.xml.soap.SOAPMessage;
import javax.xml.soap.AttachmentPart;

public class DatosCabeceraType__LiteralSerializersrc extends LiteralObjectSerializerBase implements Initializable {
    private static final QName ns1_bancoProceso_QNAME = new QName("http://bicevida.ws/services/envionominas", "bancoProceso");
    private static final QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer myns2_string__java_lang_String_String_Serializer;
    private static final QName ns1_fechaActual_QNAME = new QName("http://bicevida.ws/services/envionominas", "fechaActual");
    private static final QName ns2_date_TYPE_QNAME = SchemaConstants.QNAME_TYPE_DATE;
    private CombinedSerializer myns2_date__java_util_Calendar_DateCalendar_Serializer;
    private static final QName ns1_camposVariables_QNAME = new QName("http://bicevida.ws/services/envionominas", "camposVariables");
    private static final QName ns1_camposVariables_TYPE_QNAME = new QName("http://bicevida.ws/services/envionominas", "camposVariables");
    private CombinedSerializer myns1_camposVariables__CamposVariables__LiteralSerializersrc;
    
    public DatosCabeceraType__LiteralSerializersrc(QName type) {
        this(type,  false);
    }
    
    public DatosCabeceraType__LiteralSerializersrc(QName type, boolean encodeType) {
        super(type, true, encodeType);
        setSOAPVersion(SOAPVersion.SOAP_11);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer("", java.lang.String.class, ns2_string_TYPE_QNAME);
        myns2_date__java_util_Calendar_DateCalendar_Serializer = (CombinedSerializer)registry.getSerializer("", java.util.Calendar.class, ns2_date_TYPE_QNAME);
        myns1_camposVariables__CamposVariables__LiteralSerializersrc = (CombinedSerializer)registry.getSerializer("", cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CamposVariables.class, ns1_camposVariables_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.DatosCabeceraType instance = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.DatosCabeceraType();
        java.lang.Object member=null;
        QName elementName;
        List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        java.util.HashSet requiredElements = new java.util.HashSet();
        requiredElements.add("bancoProceso");
        requiredElements.add("fechaActual");
        requiredElements.add("camposVariables");
        for (int memberIndex = 0; memberIndex <3; memberIndex++) {
            elementName = reader.getName();
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_bancoProceso_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_bancoProceso_QNAME, reader, context);
                requiredElements.remove("bancoProceso");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setBancoProceso((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_fechaActual_QNAME))) {
                myns2_date__java_util_Calendar_DateCalendar_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_date__java_util_Calendar_DateCalendar_Serializer.deserialize(ns1_fechaActual_QNAME, reader, context);
                requiredElements.remove("fechaActual");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setFechaActual((java.util.Calendar)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_camposVariables_QNAME))) {
                myns1_camposVariables__CamposVariables__LiteralSerializersrc.setNullable( false );
                context.setNillable( false );
                member = myns1_camposVariables__CamposVariables__LiteralSerializersrc.deserialize(ns1_camposVariables_QNAME, reader, context);
                requiredElements.remove("camposVariables");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setCamposVariables((cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CamposVariables)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
        }
        if (!requiredElements.isEmpty()) {
            throw new DeserializationException( "literal.expectedElementName" , requiredElements.iterator().next().toString(), DeserializationException.FAULT_CODE_CLIENT );
        }
        
        if( reader.getState() != XMLReader.END)
        {
            reader.skipElement();
        }
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.DatosCabeceraType instance = (cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.DatosCabeceraType)obj;
        
    }
    public void doSerializeAnyAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.DatosCabeceraType instance = (cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.DatosCabeceraType)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.DatosCabeceraType instance = (cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.DatosCabeceraType)obj;
        
        myns2_string__java_lang_String_String_Serializer.setNullable( false );
        context.setNillable( false );
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getBancoProceso(), ns1_bancoProceso_QNAME, null, writer, context);
        myns2_date__java_util_Calendar_DateCalendar_Serializer.setNullable( false );
        context.setNillable( false );
        myns2_date__java_util_Calendar_DateCalendar_Serializer.serialize(instance.getFechaActual(), ns1_fechaActual_QNAME, null, writer, context);
        myns1_camposVariables__CamposVariables__LiteralSerializersrc.setNullable( false );
        context.setNillable( false );
        myns1_camposVariables__CamposVariables__LiteralSerializersrc.serialize(instance.getCamposVariables(), ns1_camposVariables_QNAME, null, writer, context);
    }
}
