// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime;

import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.common.encoding.literal.*;
import oracle.j2ee.ws.common.encoding.literal.DetailFragmentDeserializer;
import oracle.j2ee.ws.common.encoding.simpletype.*;
import oracle.j2ee.ws.common.soap.SOAPEncodingConstants;
import oracle.j2ee.ws.common.soap.SOAPEnvelopeConstants;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.common.streaming.*;
import oracle.j2ee.ws.common.wsdl.document.schema.SchemaConstants;
import oracle.j2ee.ws.common.util.xml.UUID;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.xml.soap.SOAPMessage;
import javax.xml.soap.AttachmentPart;

public class RegistroNominaType__LiteralSerializersrc extends LiteralObjectSerializerBase implements Initializable {
    private static final QName ns1_idRegistro_QNAME = new QName("http://bicevida.ws/services/envionominas", "idRegistro");
    private static final QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer myns2_string__java_lang_String_String_Serializer;
    private static final QName ns1_rut_QNAME = new QName("http://bicevida.ws/services/envionominas", "rut");
    private static final QName ns1_digitoVerificador_QNAME = new QName("http://bicevida.ws/services/envionominas", "digitoVerificador");
    private static final QName ns1_nombre_QNAME = new QName("http://bicevida.ws/services/envionominas", "nombre");
    private static final QName ns1_formaPago_QNAME = new QName("http://bicevida.ws/services/envionominas", "formaPago");
    private static final QName ns1_banco_QNAME = new QName("http://bicevida.ws/services/envionominas", "banco");
    private static final QName ns1_cuenta_QNAME = new QName("http://bicevida.ws/services/envionominas", "cuenta");
    private static final QName ns1_numeroDocumentoPago_QNAME = new QName("http://bicevida.ws/services/envionominas", "numeroDocumentoPago");
    private static final QName ns1_monto_QNAME = new QName("http://bicevida.ws/services/envionominas", "monto");
    private static final QName ns1_oficinaDestino_QNAME = new QName("http://bicevida.ws/services/envionominas", "oficinaDestino");
    private static final QName ns1_fechaMovimiento_QNAME = new QName("http://bicevida.ws/services/envionominas", "fechaMovimiento");
    private static final QName ns2_date_TYPE_QNAME = SchemaConstants.QNAME_TYPE_DATE;
    private CombinedSerializer myns2_date__java_util_Calendar_DateCalendar_Serializer;
    private static final QName ns1_tipoDocumentoPago_QNAME = new QName("http://bicevida.ws/services/envionominas", "tipoDocumentoPago");
    private static final QName ns1_glosa_QNAME = new QName("http://bicevida.ws/services/envionominas", "glosa");
    private static final QName ns1_estadoPago_QNAME = new QName("http://bicevida.ws/services/envionominas", "estadoPago");
    private static final QName ns1_tipoCuenta_QNAME = new QName("http://bicevida.ws/services/envionominas", "tipoCuenta");
    
    public RegistroNominaType__LiteralSerializersrc(QName type) {
        this(type,  false);
    }
    
    public RegistroNominaType__LiteralSerializersrc(QName type, boolean encodeType) {
        super(type, true, encodeType);
        setSOAPVersion(SOAPVersion.SOAP_11);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer("", java.lang.String.class, ns2_string_TYPE_QNAME);
        myns2_date__java_util_Calendar_DateCalendar_Serializer = (CombinedSerializer)registry.getSerializer("", java.util.Calendar.class, ns2_date_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RegistroNominaType instance = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RegistroNominaType();
        java.lang.Object member=null;
        QName elementName;
        List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        java.util.HashSet requiredElements = new java.util.HashSet();
        requiredElements.add("rut");
        requiredElements.add("digitoVerificador");
        requiredElements.add("nombre");
        requiredElements.add("banco");
        requiredElements.add("cuenta");
        requiredElements.add("monto");
        for (int memberIndex = 0; memberIndex <15; memberIndex++) {
            elementName = reader.getName();
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_idRegistro_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( true );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_idRegistro_QNAME, reader, context);
                requiredElements.remove("idRegistro");
                instance.setIdRegistro((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_rut_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_rut_QNAME, reader, context);
                requiredElements.remove("rut");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setRut((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_digitoVerificador_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_digitoVerificador_QNAME, reader, context);
                requiredElements.remove("digitoVerificador");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setDigitoVerificador((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_nombre_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_nombre_QNAME, reader, context);
                requiredElements.remove("nombre");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setNombre((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_formaPago_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_formaPago_QNAME, reader, context);
                requiredElements.remove("formaPago");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setFormaPago((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_banco_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_banco_QNAME, reader, context);
                requiredElements.remove("banco");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setBanco((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_cuenta_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_cuenta_QNAME, reader, context);
                requiredElements.remove("cuenta");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setCuenta((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_numeroDocumentoPago_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_numeroDocumentoPago_QNAME, reader, context);
                requiredElements.remove("numeroDocumentoPago");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setNumeroDocumentoPago((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_monto_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_monto_QNAME, reader, context);
                requiredElements.remove("monto");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setMonto((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_oficinaDestino_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_oficinaDestino_QNAME, reader, context);
                requiredElements.remove("oficinaDestino");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setOficinaDestino((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_fechaMovimiento_QNAME))) {
                myns2_date__java_util_Calendar_DateCalendar_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_date__java_util_Calendar_DateCalendar_Serializer.deserialize(ns1_fechaMovimiento_QNAME, reader, context);
                requiredElements.remove("fechaMovimiento");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setFechaMovimiento((java.util.Calendar)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_tipoDocumentoPago_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_tipoDocumentoPago_QNAME, reader, context);
                requiredElements.remove("tipoDocumentoPago");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setTipoDocumentoPago((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_glosa_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_glosa_QNAME, reader, context);
                requiredElements.remove("glosa");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setGlosa((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_estadoPago_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_estadoPago_QNAME, reader, context);
                requiredElements.remove("estadoPago");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setEstadoPago((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_tipoCuenta_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_tipoCuenta_QNAME, reader, context);
                requiredElements.remove("tipoCuenta");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setTipoCuenta((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
        }
        if (!requiredElements.isEmpty()) {
            throw new DeserializationException( "literal.expectedElementName" , requiredElements.iterator().next().toString(), DeserializationException.FAULT_CODE_CLIENT );
        }
        
        if( reader.getState() != XMLReader.END)
        {
            reader.skipElement();
        }
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RegistroNominaType instance = (cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RegistroNominaType)obj;
        
    }
    public void doSerializeAnyAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RegistroNominaType instance = (cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RegistroNominaType)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RegistroNominaType instance = (cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RegistroNominaType)obj;
        
        myns2_string__java_lang_String_String_Serializer.setNullable( false );
        context.setNillable( true );
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getIdRegistro(), ns1_idRegistro_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.setNullable( false );
        context.setNillable( false );
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getRut(), ns1_rut_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.setNullable( false );
        context.setNillable( false );
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getDigitoVerificador(), ns1_digitoVerificador_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.setNullable( false );
        context.setNillable( false );
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getNombre(), ns1_nombre_QNAME, null, writer, context);
        if (instance.getFormaPago() != null) {
            myns2_string__java_lang_String_String_Serializer.setNullable( false );
            context.setNillable( false );
            myns2_string__java_lang_String_String_Serializer.serialize(instance.getFormaPago(), ns1_formaPago_QNAME, null, writer, context);
        }
        myns2_string__java_lang_String_String_Serializer.setNullable( false );
        context.setNillable( false );
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getBanco(), ns1_banco_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.setNullable( false );
        context.setNillable( false );
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getCuenta(), ns1_cuenta_QNAME, null, writer, context);
        if (instance.getNumeroDocumentoPago() != null) {
            myns2_string__java_lang_String_String_Serializer.setNullable( false );
            context.setNillable( false );
            myns2_string__java_lang_String_String_Serializer.serialize(instance.getNumeroDocumentoPago(), ns1_numeroDocumentoPago_QNAME, null, writer, context);
        }
        myns2_string__java_lang_String_String_Serializer.setNullable( false );
        context.setNillable( false );
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getMonto(), ns1_monto_QNAME, null, writer, context);
        if (instance.getOficinaDestino() != null) {
            myns2_string__java_lang_String_String_Serializer.setNullable( false );
            context.setNillable( false );
            myns2_string__java_lang_String_String_Serializer.serialize(instance.getOficinaDestino(), ns1_oficinaDestino_QNAME, null, writer, context);
        }
        if (instance.getFechaMovimiento() != null) {
            myns2_date__java_util_Calendar_DateCalendar_Serializer.setNullable( false );
            context.setNillable( false );
            myns2_date__java_util_Calendar_DateCalendar_Serializer.serialize(instance.getFechaMovimiento(), ns1_fechaMovimiento_QNAME, null, writer, context);
        }
        if (instance.getTipoDocumentoPago() != null) {
            myns2_string__java_lang_String_String_Serializer.setNullable( false );
            context.setNillable( false );
            myns2_string__java_lang_String_String_Serializer.serialize(instance.getTipoDocumentoPago(), ns1_tipoDocumentoPago_QNAME, null, writer, context);
        }
        if (instance.getGlosa() != null) {
            myns2_string__java_lang_String_String_Serializer.setNullable( false );
            context.setNillable( false );
            myns2_string__java_lang_String_String_Serializer.serialize(instance.getGlosa(), ns1_glosa_QNAME, null, writer, context);
        }
        if (instance.getEstadoPago() != null) {
            myns2_string__java_lang_String_String_Serializer.setNullable( false );
            context.setNillable( false );
            myns2_string__java_lang_String_String_Serializer.serialize(instance.getEstadoPago(), ns1_estadoPago_QNAME, null, writer, context);
        }
        if (instance.getTipoCuenta() != null) {
            myns2_string__java_lang_String_String_Serializer.setNullable( false );
            context.setNillable( false );
            myns2_string__java_lang_String_String_Serializer.serialize(instance.getTipoCuenta(), ns1_tipoCuenta_QNAME, null, writer, context);
        }
    }
}
