// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)
package cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime;

import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.common.encoding.literal.*;
import oracle.j2ee.ws.common.encoding.literal.DetailFragmentDeserializer;
import oracle.j2ee.ws.common.encoding.simpletype.*;
import oracle.j2ee.ws.common.soap.SOAPEncodingConstants;
import oracle.j2ee.ws.common.soap.SOAPEnvelopeConstants;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.common.streaming.*;
import oracle.j2ee.ws.common.wsdl.document.schema.SchemaConstants;
import oracle.j2ee.ws.common.util.xml.UUID;

import javax.xml.namespace.QName;

import java.util.List;
import java.util.ArrayList;
import java.util.StringTokenizer;

import javax.xml.soap.SOAPMessage;
import javax.xml.soap.AttachmentPart;

public class Nominas_LiteralSerializersrc extends LiteralObjectSerializerBase implements Initializable {
    private static final QName ns1_nomina_QNAME = new QName( "http://bicevida.ws/services/envionominas", "nomina" );
    private static final QName ns1_NominaType_TYPE_QNAME = new QName( "http://bicevida.ws/services/envionominas", "NominaType" );
    private CombinedSerializer myns1_NominaType__NominaType__LiteralSerializersrc;

    public Nominas_LiteralSerializersrc( QName type ) {
        this( type, false );
    }

    public Nominas_LiteralSerializersrc( QName type, boolean encodeType ) {
        super( type, true, encodeType );
        setSOAPVersion( SOAPVersion.SOAP_11 );
    }

    public void initialize( InternalTypeMappingRegistry registry ) throws Exception {
        myns1_NominaType__NominaType__LiteralSerializersrc = ( CombinedSerializer ) registry.getSerializer( "", cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.NominaType.class, ns1_NominaType_TYPE_QNAME );
    }

    public java.lang.Object doDeserialize( XMLReader reader, SOAPDeserializationContext context ) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.Nominas instance = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.Nominas();
        java.lang.Object member = null;
        QName elementName;
        List values;
        java.lang.Object value;
        reader.nextElementContent();
        java.util.HashSet requiredElements = new java.util.HashSet();
        elementName = reader.getName();
        if ( ( reader.getState() == XMLReader.START ) && ( matchQName( elementName, ns1_nomina_QNAME ) ) ) {
            values = new ArrayList();
            for ( ; ; ) {
                elementName = reader.getName();
                if ( ( reader.getState() == XMLReader.START ) && ( matchQName( elementName, ns1_nomina_QNAME ) ) ) {
                    myns1_NominaType__NominaType__LiteralSerializersrc.setNullable( false );
                    context.setNillable( true );
                    value = myns1_NominaType__NominaType__LiteralSerializersrc.deserialize( ns1_nomina_QNAME, reader, context );
                    requiredElements.remove( "nomina" );
                    values.add( value );
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.NominaType[ values.size() ];
            member = values.toArray( ( java.lang.Object[] ) member );
            instance.setNomina( ( cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.NominaType[] ) member );
        } else {
            if ( instance.getNomina() == null )
                instance.setNomina( new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.NominaType[ 0 ] );
        }
        if ( !requiredElements.isEmpty() ) {
            throw new DeserializationException( "literal.expectedElementName", requiredElements.iterator().next().toString(), DeserializationException.FAULT_CODE_CLIENT );
        }
        if ( reader.getState() != XMLReader.END ) {
            reader.skipElement();
        }
        XMLReaderUtil.verifyReaderState( reader, XMLReader.END );
        return ( java.lang.Object ) instance;
    }

    public void doSerializeAttributes( java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context ) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.Nominas instance = ( cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.Nominas ) obj;
    }

    public void doSerializeAnyAttributes( java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context ) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.Nominas instance = ( cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.Nominas ) obj;
    }

    public void doSerialize( java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context ) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.Nominas instance = ( cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.Nominas ) obj;
        if ( instance.getNomina() != null ) {
            for ( int i = 0; i < instance.getNomina().length; ++i ) {
                myns1_NominaType__NominaType__LiteralSerializersrc.setNullable( false );
                context.setNillable( true );
                myns1_NominaType__NominaType__LiteralSerializersrc.serialize( instance.getNomina()[ i ], ns1_nomina_QNAME, null, writer, context );
            }
        }
    }
}
