// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime;

import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.common.encoding.literal.*;
import oracle.j2ee.ws.common.encoding.literal.DetailFragmentDeserializer;
import oracle.j2ee.ws.common.encoding.simpletype.*;
import oracle.j2ee.ws.common.soap.SOAPEncodingConstants;
import oracle.j2ee.ws.common.soap.SOAPEnvelopeConstants;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.common.streaming.*;
import oracle.j2ee.ws.common.wsdl.document.schema.SchemaConstants;
import oracle.j2ee.ws.common.util.xml.UUID;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.xml.soap.SOAPMessage;
import javax.xml.soap.AttachmentPart;

public class NominaType__LiteralSerializersrc extends LiteralObjectSerializerBase implements Initializable {
    private static final QName ns1_idNomina_QNAME = new QName("http://bicevida.ws/services/envionominas", "idNomina");
    private static final QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer myns2_string__java_lang_String_String_Serializer;
    private static final QName ns1_idProceso_QNAME = new QName("http://bicevida.ws/services/envionominas", "idProceso");
    private static final QName ns1_folioProceso_QNAME = new QName("http://bicevida.ws/services/envionominas", "folioProceso");
    private static final QName ns1_fechaPago_QNAME = new QName("http://bicevida.ws/services/envionominas", "fechaPago");
    private static final QName ns2_date_TYPE_QNAME = SchemaConstants.QNAME_TYPE_DATE;
    private CombinedSerializer myns2_date__java_util_Calendar_DateCalendar_Serializer;
    private static final QName ns1_registrosNomina_QNAME = new QName("http://bicevida.ws/services/envionominas", "registrosNomina");
    private static final QName ns1_registrosNomina_TYPE_QNAME = new QName("http://bicevida.ws/services/envionominas", "registrosNomina");
    private CombinedSerializer myns1_registrosNomina__RegistrosNomina__LiteralSerializersrc;
    
    public NominaType__LiteralSerializersrc(QName type) {
        this(type,  false);
    }
    
    public NominaType__LiteralSerializersrc(QName type, boolean encodeType) {
        super(type, true, encodeType);
        setSOAPVersion(SOAPVersion.SOAP_11);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer("", java.lang.String.class, ns2_string_TYPE_QNAME);
        myns2_date__java_util_Calendar_DateCalendar_Serializer = (CombinedSerializer)registry.getSerializer("", java.util.Calendar.class, ns2_date_TYPE_QNAME);
        myns1_registrosNomina__RegistrosNomina__LiteralSerializersrc = (CombinedSerializer)registry.getSerializer("", cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RegistrosNomina.class, ns1_registrosNomina_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.NominaType instance = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.NominaType();
        java.lang.Object member=null;
        QName elementName;
        List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        java.util.HashSet requiredElements = new java.util.HashSet();
        requiredElements.add("registrosNomina");
        for (int memberIndex = 0; memberIndex <5; memberIndex++) {
            elementName = reader.getName();
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_idNomina_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_idNomina_QNAME, reader, context);
                requiredElements.remove("idNomina");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setIdNomina((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_idProceso_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_idProceso_QNAME, reader, context);
                requiredElements.remove("idProceso");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setIdProceso((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_folioProceso_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_folioProceso_QNAME, reader, context);
                requiredElements.remove("folioProceso");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setFolioProceso((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_fechaPago_QNAME))) {
                myns2_date__java_util_Calendar_DateCalendar_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_date__java_util_Calendar_DateCalendar_Serializer.deserialize(ns1_fechaPago_QNAME, reader, context);
                requiredElements.remove("fechaPago");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setFechaPago((java.util.Calendar)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_registrosNomina_QNAME))) {
                myns1_registrosNomina__RegistrosNomina__LiteralSerializersrc.setNullable( false );
                context.setNillable( true );
                member = myns1_registrosNomina__RegistrosNomina__LiteralSerializersrc.deserialize(ns1_registrosNomina_QNAME, reader, context);
                requiredElements.remove("registrosNomina");
                instance.setRegistrosNomina((cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RegistrosNomina)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
        }
        if (!requiredElements.isEmpty()) {
            throw new DeserializationException( "literal.expectedElementName" , requiredElements.iterator().next().toString(), DeserializationException.FAULT_CODE_CLIENT );
        }
        
        if( reader.getState() != XMLReader.END)
        {
            reader.skipElement();
        }
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.NominaType instance = (cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.NominaType)obj;
        
    }
    public void doSerializeAnyAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.NominaType instance = (cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.NominaType)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.NominaType instance = (cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.NominaType)obj;
        
        if (instance.getIdNomina() != null) {
            myns2_string__java_lang_String_String_Serializer.setNullable( false );
            context.setNillable( false );
            myns2_string__java_lang_String_String_Serializer.serialize(instance.getIdNomina(), ns1_idNomina_QNAME, null, writer, context);
        }
        if (instance.getIdProceso() != null) {
            myns2_string__java_lang_String_String_Serializer.setNullable( false );
            context.setNillable( false );
            myns2_string__java_lang_String_String_Serializer.serialize(instance.getIdProceso(), ns1_idProceso_QNAME, null, writer, context);
        }
        if (instance.getFolioProceso() != null) {
            myns2_string__java_lang_String_String_Serializer.setNullable( false );
            context.setNillable( false );
            myns2_string__java_lang_String_String_Serializer.serialize(instance.getFolioProceso(), ns1_folioProceso_QNAME, null, writer, context);
        }
        if (instance.getFechaPago() != null) {
            myns2_date__java_util_Calendar_DateCalendar_Serializer.setNullable( false );
            context.setNillable( false );
            myns2_date__java_util_Calendar_DateCalendar_Serializer.serialize(instance.getFechaPago(), ns1_fechaPago_QNAME, null, writer, context);
        }
        myns1_registrosNomina__RegistrosNomina__LiteralSerializersrc.setNullable( false );
        context.setNillable( true );
        myns1_registrosNomina__RegistrosNomina__LiteralSerializersrc.serialize(instance.getRegistrosNomina(), ns1_registrosNomina_QNAME, null, writer, context);
    }
}
