// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.runtime;

import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.common.encoding.literal.*;
import oracle.j2ee.ws.common.encoding.literal.DetailFragmentDeserializer;
import oracle.j2ee.ws.common.encoding.simpletype.*;
import oracle.j2ee.ws.common.soap.SOAPEncodingConstants;
import oracle.j2ee.ws.common.soap.SOAPEnvelopeConstants;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.common.streaming.*;
import oracle.j2ee.ws.common.wsdl.document.schema.SchemaConstants;
import oracle.j2ee.ws.common.util.xml.UUID;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.xml.soap.SOAPMessage;
import javax.xml.soap.AttachmentPart;

public class RindeNominaInputType__LiteralSerializersrc extends LiteralObjectSerializerBase implements Initializable {
    private static final QName ns1_datosCabecera_QNAME = new QName("http://bicevida.ws/services/envionominas", "datosCabecera");
    private static final QName ns1_DatosCabeceraType_TYPE_QNAME = new QName("http://bicevida.ws/services/envionominas", "DatosCabeceraType");
    private CombinedSerializer myns1_DatosCabeceraType__DatosCabeceraType__LiteralSerializersrc;
    private static final QName ns1_fecha_QNAME = new QName("http://bicevida.ws/services/envionominas", "fecha");
    private static final QName ns2_date_TYPE_QNAME = SchemaConstants.QNAME_TYPE_DATE;
    private CombinedSerializer myns2_date__java_util_Calendar_DateCalendar_Serializer;
    private static final QName ns1_idNomina_QNAME = new QName("http://bicevida.ws/services/envionominas", "idNomina");
    private static final QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer myns2_string__java_lang_String_String_Serializer;
    private static final QName ns1_idProceso_QNAME = new QName("http://bicevida.ws/services/envionominas", "idProceso");
    private static final QName ns1_tipoRendicion_QNAME = new QName("http://bicevida.ws/services/envionominas", "tipoRendicion");
    
    public RindeNominaInputType__LiteralSerializersrc(QName type) {
        this(type,  false);
    }
    
    public RindeNominaInputType__LiteralSerializersrc(QName type, boolean encodeType) {
        super(type, true, encodeType);
        setSOAPVersion(SOAPVersion.SOAP_11);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        myns1_DatosCabeceraType__DatosCabeceraType__LiteralSerializersrc = (CombinedSerializer)registry.getSerializer("", cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.DatosCabeceraType.class, ns1_DatosCabeceraType_TYPE_QNAME);
        myns2_date__java_util_Calendar_DateCalendar_Serializer = (CombinedSerializer)registry.getSerializer("", java.util.Calendar.class, ns2_date_TYPE_QNAME);
        myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer("", java.lang.String.class, ns2_string_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RindeNominaInputType instance = new cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RindeNominaInputType();
        java.lang.Object member=null;
        QName elementName;
        List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        java.util.HashSet requiredElements = new java.util.HashSet();
        requiredElements.add("datosCabecera");
        requiredElements.add("fecha");
        requiredElements.add("idNomina");
        requiredElements.add("idProceso");
        requiredElements.add("tipoRendicion");
        for (int memberIndex = 0; memberIndex <5; memberIndex++) {
            elementName = reader.getName();
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_datosCabecera_QNAME))) {
                myns1_DatosCabeceraType__DatosCabeceraType__LiteralSerializersrc.setNullable( false );
                context.setNillable( false );
                member = myns1_DatosCabeceraType__DatosCabeceraType__LiteralSerializersrc.deserialize(ns1_datosCabecera_QNAME, reader, context);
                requiredElements.remove("datosCabecera");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setDatosCabecera((cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.DatosCabeceraType)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_fecha_QNAME))) {
                myns2_date__java_util_Calendar_DateCalendar_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_date__java_util_Calendar_DateCalendar_Serializer.deserialize(ns1_fecha_QNAME, reader, context);
                requiredElements.remove("fecha");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setFecha((java.util.Calendar)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_idNomina_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_idNomina_QNAME, reader, context);
                requiredElements.remove("idNomina");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setIdNomina((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_idProceso_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( true );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_idProceso_QNAME, reader, context);
                requiredElements.remove("idProceso");
                instance.setIdProceso((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
            if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_tipoRendicion_QNAME))) {
                myns2_string__java_lang_String_String_Serializer.setNullable( false );
                context.setNillable( false );
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_tipoRendicion_QNAME, reader, context);
                requiredElements.remove("tipoRendicion");
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull",DeserializationException.FAULT_CODE_CLIENT);
                }
                instance.setTipoRendicion((java.lang.String)member);
                context.setXmlFragmentWrapperName( null );
                reader.nextElementContent();
            }
        }
        if (!requiredElements.isEmpty()) {
            throw new DeserializationException( "literal.expectedElementName" , requiredElements.iterator().next().toString(), DeserializationException.FAULT_CODE_CLIENT );
        }
        
        if( reader.getState() != XMLReader.END)
        {
            reader.skipElement();
        }
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RindeNominaInputType instance = (cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RindeNominaInputType)obj;
        
    }
    public void doSerializeAnyAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RindeNominaInputType instance = (cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RindeNominaInputType)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RindeNominaInputType instance = (cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RindeNominaInputType)obj;
        
        myns1_DatosCabeceraType__DatosCabeceraType__LiteralSerializersrc.setNullable( false );
        context.setNillable( false );
        myns1_DatosCabeceraType__DatosCabeceraType__LiteralSerializersrc.serialize(instance.getDatosCabecera(), ns1_datosCabecera_QNAME, null, writer, context);
        myns2_date__java_util_Calendar_DateCalendar_Serializer.setNullable( false );
        context.setNillable( false );
        myns2_date__java_util_Calendar_DateCalendar_Serializer.serialize(instance.getFecha(), ns1_fecha_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.setNullable( false );
        context.setNillable( false );
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getIdNomina(), ns1_idNomina_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.setNullable( false );
        context.setNillable( true );
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getIdProceso(), ns1_idProceso_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.setNullable( false );
        context.setNillable( false );
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getTipoRendicion(), ns1_tipoRendicion_QNAME, null, writer, context);
    }
}
