// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.services.ws.proxy.runtime;


import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.common.soap.SOAPEncodingConstants;
import oracle.j2ee.ws.common.soap.message.SOAPFaultInfo;
import oracle.j2ee.ws.common.streaming.*;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.common.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class EnvioNominasPort_cargar_Fault_SOAPSerializer extends SOAPFaultInfoSerializer {
    private static final QName ns1_EnvioNominasFault_QNAME = new QName("http://bicevida.ws/services/envionominas", "EnvioNominasFault");
    private static final QName ns1_ErrorType_TYPE_QNAME = new QName("http://bicevida.ws/services/envionominas", "ErrorType");
    private CombinedSerializer myns1_ErrorType__ErrorType__LiteralSerializersrc;
    private CombinedSerializer myns1_ErrorType__ErrorType__LiteralSerializersrc_Serializer;
    private static final int cl_bicevida_envionominas_model_types_ws_bicevida_services_envionominas_ErrorType_INDEX = 0;
    
    public EnvioNominasPort_cargar_Fault_SOAPSerializer(boolean encodeType, boolean isNullable, SOAPVersion soapVersion) {
        super(encodeType, isNullable, soapVersion);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        super.initialize(registry);
        myns1_ErrorType__ErrorType__LiteralSerializersrc = (CombinedSerializer)registry.getSerializer("", cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.ErrorType.class, ns1_ErrorType_TYPE_QNAME);
        myns1_ErrorType__ErrorType__LiteralSerializersrc_Serializer = myns1_ErrorType__ErrorType__LiteralSerializersrc.getInnermostSerializer();
    }
    
    protected Object deserializeDetail(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context, SOAPFaultInfo instance) throws Exception {
        boolean isComplete = true;
        QName elementName;
        QName elementType = null;
        SOAPInstanceBuilder builder = null;
        Object detail = null;
        Object obj = null;
        
        reader.nextElementContent();
        if (reader.getState() == XMLReader.END)
            return deserializeDetail(reader, context);
        XMLReaderUtil.verifyReaderState(reader, XMLReader.START);
        elementName = reader.getName();
        elementType = getType(reader);
        if (elementName.getLocalPart().equals(ns1_EnvioNominasFault_QNAME.getLocalPart())) {
            if (elementType == null || 
                (elementType.equals(myns1_ErrorType__ErrorType__LiteralSerializersrc.getXmlType()) ||
                (myns1_ErrorType__ErrorType__LiteralSerializersrc instanceof ArraySerializerBase &&
                (elementType.equals(SOAPEncodingConstants.getSOAPEncodingConstants(SOAPVersion.SOAP_11).getQNameEncodingArray()) ||
                 elementType.equals(SOAPEncodingConstants.getSOAPEncodingConstants(SOAPVersion.SOAP_12).getQNameEncodingArray())) ) ) ){
                obj = myns1_ErrorType__ErrorType__LiteralSerializersrc.deserialize(ns1_EnvioNominasFault_QNAME, reader, context);
                detail = obj;
                reader.nextElementContent();
                if( reader.getState() != XMLReader.END)
                {
                    reader.skipElement();
                }
                XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
                return (isComplete ? (Object)detail : (Object)state);
            } 
        }
        return deserializeDetail(reader, context);
    }
    
    protected void serializeDetail(Object detail, XMLWriter writer, SOAPSerializationContext context)
        throws Exception {
        if (detail == null) {
            throw new SerializationException("soap.unexpectedNull");
        }
        if(context.getSOAPVersion().equals(SOAPVersion.SOAP_11)){
            writer.startElement(DETAIL_QNAME);
        }
        else{
            writer.startElement(DETAIL12_QNAME);
        }
        
        boolean pushedEncodingStyle = false;
        if (encodingStyle != null) {
            context.pushEncodingStyle(encodingStyle, writer);
        }
        if (detail instanceof cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.ErrorType) {
            myns1_ErrorType__ErrorType__LiteralSerializersrc_Serializer.serialize(detail, ns1_EnvioNominasFault_QNAME, null, writer, context);
        }
        writer.endElement();
        if (pushedEncodingStyle) {
            context.popEncodingStyle();
        }
    }
}
