// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.proxy.bdclientes.consultas;

import javax.xml.rpc.*;

public interface WSClientesConsultaFaseTres_Service extends javax.xml.rpc.Service {
    public cl.bicevida.core.model.services.ws.proxy.bdclientes.consultas.WSClientesConsultaFaseTres_PortType getWSClientesConsultaFaseTresSoapHttpPort() throws javax.xml.rpc.ServiceException;
}
