// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.proxy.bdclientes.consultas;

public interface WSClientesConsultaFaseTres_PortType extends java.rmi.Remote {
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.RetConsultaContratoCanalRemoto consultaContratoCanalRemoto(java.lang.String rut) throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.RetDireccion consultaDireccion(java.lang.String idDireccion) throws 
         java.rmi.RemoteException;
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.RetPersona consultaPersona(java.lang.String rut) throws 
         java.rmi.RemoteException;
}
