// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types;


public class ActividadModel implements java.io.Serializable {
    protected java.lang.String descripcion;
    protected java.lang.String codigo;
    
    public ActividadModel() {
    }
    
    public java.lang.String getDescripcion() {
        return descripcion;
    }
    
    public void setDescripcion(java.lang.String descripcion) {
        this.descripcion = descripcion;
    }
    
    public java.lang.String getCodigo() {
        return codigo;
    }
    
    public void setCodigo(java.lang.String codigo) {
        this.codigo = codigo;
    }
}
