// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types;


public class ComunaModel implements java.io.Serializable {
    protected java.lang.String descripcionComuna;
    protected java.lang.String codigoProvincia;
    protected java.lang.String codigoRegion;
    protected java.lang.String codigoComuna;
    protected java.lang.String descripcionProvincia;
    protected java.lang.String descripcionRegion;
    protected java.lang.String codigoArea;
    
    public ComunaModel() {
    }
    
    public java.lang.String getDescripcionComuna() {
        return descripcionComuna;
    }
    
    public void setDescripcionComuna(java.lang.String descripcionComuna) {
        this.descripcionComuna = descripcionComuna;
    }
    
    public java.lang.String getCodigoProvincia() {
        return codigoProvincia;
    }
    
    public void setCodigoProvincia(java.lang.String codigoProvincia) {
        this.codigoProvincia = codigoProvincia;
    }
    
    public java.lang.String getCodigoRegion() {
        return codigoRegion;
    }
    
    public void setCodigoRegion(java.lang.String codigoRegion) {
        this.codigoRegion = codigoRegion;
    }
    
    public java.lang.String getCodigoComuna() {
        return codigoComuna;
    }
    
    public void setCodigoComuna(java.lang.String codigoComuna) {
        this.codigoComuna = codigoComuna;
    }
    
    public java.lang.String getDescripcionProvincia() {
        return descripcionProvincia;
    }
    
    public void setDescripcionProvincia(java.lang.String descripcionProvincia) {
        this.descripcionProvincia = descripcionProvincia;
    }
    
    public java.lang.String getDescripcionRegion() {
        return descripcionRegion;
    }
    
    public void setDescripcionRegion(java.lang.String descripcionRegion) {
        this.descripcionRegion = descripcionRegion;
    }
    
    public java.lang.String getCodigoArea() {
        return codigoArea;
    }
    
    public void setCodigoArea(java.lang.String codigoArea) {
        this.codigoArea = codigoArea;
    }
}
