// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types;


public class ConsultaPersonaElement implements java.io.Serializable {
    protected java.lang.String rut;
    
    public ConsultaPersonaElement() {
    }
    
    public java.lang.String getRut() {
        return rut;
    }
    
    public void setRut(java.lang.String rut) {
        this.rut = rut;
    }
}
