// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types;


public class PersonaModel implements java.io.Serializable {
    protected java.lang.String rut;
    protected java.lang.String dv;
    protected java.lang.String nombres;
    protected java.lang.String apellidoPaterno;
    protected java.lang.String apellidoMaterno;
    protected java.lang.String fechaNacimiento;
    protected cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.EstadoCivilModel estadoCivil;
    protected cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.SexoModel sexo;
    protected cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.TipoPersonaModel tipoPersona;
    protected java.lang.String contratoFirmado;
    protected cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.GSEModel gse;
    protected java.lang.String seEnviaMail;
    protected java.lang.String EMail;
    protected java.lang.String noTieneEMail;
    protected cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.NivelEducacionalModel nivelEducacional;
    protected cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ActividadModel actividad;
    protected cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.AFPModel afp;
    protected cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.IsapreModel isapre;
    protected cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.NacionalidadModel nacionalidad;
    protected java.lang.String fechaDefuncion;
    protected java.lang.String mensajeriaSms;
    protected cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ProfesionModel profesion;
    protected cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.OcupacionModel ocupacion;
    protected cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.NivelIngresoModel nivelIngreso;
    protected java.lang.String usuarioCreacion;
    protected java.lang.String origenCliente;
    protected cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.DireccionModel[] direcciones;
    
    public PersonaModel() {
    }
    
    public java.lang.String getRut() {
        return rut;
    }
    
    public void setRut(java.lang.String rut) {
        this.rut = rut;
    }
    
    public java.lang.String getDv() {
        return dv;
    }
    
    public void setDv(java.lang.String dv) {
        this.dv = dv;
    }
    
    public java.lang.String getNombres() {
        return nombres;
    }
    
    public void setNombres(java.lang.String nombres) {
        this.nombres = nombres;
    }
    
    public java.lang.String getApellidoPaterno() {
        return apellidoPaterno;
    }
    
    public void setApellidoPaterno(java.lang.String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    
    public java.lang.String getApellidoMaterno() {
        return apellidoMaterno;
    }
    
    public void setApellidoMaterno(java.lang.String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    
    public java.lang.String getFechaNacimiento() {
        return fechaNacimiento;
    }
    
    public void setFechaNacimiento(java.lang.String fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.EstadoCivilModel getEstadoCivil() {
        return estadoCivil;
    }
    
    public void setEstadoCivil(cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.EstadoCivilModel estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.SexoModel getSexo() {
        return sexo;
    }
    
    public void setSexo(cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.SexoModel sexo) {
        this.sexo = sexo;
    }
    
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.TipoPersonaModel getTipoPersona() {
        return tipoPersona;
    }
    
    public void setTipoPersona(cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.TipoPersonaModel tipoPersona) {
        this.tipoPersona = tipoPersona;
    }
    
    public java.lang.String getContratoFirmado() {
        return contratoFirmado;
    }
    
    public void setContratoFirmado(java.lang.String contratoFirmado) {
        this.contratoFirmado = contratoFirmado;
    }
    
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.GSEModel getGse() {
        return gse;
    }
    
    public void setGse(cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.GSEModel gse) {
        this.gse = gse;
    }
    
    public java.lang.String getSeEnviaMail() {
        return seEnviaMail;
    }
    
    public void setSeEnviaMail(java.lang.String seEnviaMail) {
        this.seEnviaMail = seEnviaMail;
    }
    
    public java.lang.String getEMail() {
        return EMail;
    }
    
    public void setEMail(java.lang.String EMail) {
        this.EMail = EMail;
    }
    
    public java.lang.String getNoTieneEMail() {
        return noTieneEMail;
    }
    
    public void setNoTieneEMail(java.lang.String noTieneEMail) {
        this.noTieneEMail = noTieneEMail;
    }
    
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.NivelEducacionalModel getNivelEducacional() {
        return nivelEducacional;
    }
    
    public void setNivelEducacional(cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.NivelEducacionalModel nivelEducacional) {
        this.nivelEducacional = nivelEducacional;
    }
    
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ActividadModel getActividad() {
        return actividad;
    }
    
    public void setActividad(cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ActividadModel actividad) {
        this.actividad = actividad;
    }
    
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.AFPModel getAfp() {
        return afp;
    }
    
    public void setAfp(cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.AFPModel afp) {
        this.afp = afp;
    }
    
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.IsapreModel getIsapre() {
        return isapre;
    }
    
    public void setIsapre(cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.IsapreModel isapre) {
        this.isapre = isapre;
    }
    
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.NacionalidadModel getNacionalidad() {
        return nacionalidad;
    }
    
    public void setNacionalidad(cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.NacionalidadModel nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    
    public java.lang.String getFechaDefuncion() {
        return fechaDefuncion;
    }
    
    public void setFechaDefuncion(java.lang.String fechaDefuncion) {
        this.fechaDefuncion = fechaDefuncion;
    }
    
    public java.lang.String getMensajeriaSms() {
        return mensajeriaSms;
    }
    
    public void setMensajeriaSms(java.lang.String mensajeriaSms) {
        this.mensajeriaSms = mensajeriaSms;
    }
    
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ProfesionModel getProfesion() {
        return profesion;
    }
    
    public void setProfesion(cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ProfesionModel profesion) {
        this.profesion = profesion;
    }
    
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.OcupacionModel getOcupacion() {
        return ocupacion;
    }
    
    public void setOcupacion(cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.OcupacionModel ocupacion) {
        this.ocupacion = ocupacion;
    }
    
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.NivelIngresoModel getNivelIngreso() {
        return nivelIngreso;
    }
    
    public void setNivelIngreso(cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.NivelIngresoModel nivelIngreso) {
        this.nivelIngreso = nivelIngreso;
    }
    
    public java.lang.String getUsuarioCreacion() {
        return usuarioCreacion;
    }
    
    public void setUsuarioCreacion(java.lang.String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }
    
    public java.lang.String getOrigenCliente() {
        return origenCliente;
    }
    
    public void setOrigenCliente(java.lang.String origenCliente) {
        this.origenCliente = origenCliente;
    }
    
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.DireccionModel[] getDirecciones() {
        return direcciones;
    }
    
    public void setDirecciones(cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.DireccionModel[] direcciones) {
        this.direcciones = direcciones;
    }
}
