// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.services.ws.proxy;

public interface EnvioNominasPort extends java.rmi.Remote {
    public cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CargaNominaOutputType cargar(cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CargaNominaInputType cargaNominaInput) throws 
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.ErrorType,  java.rmi.RemoteException;
    public cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RindeNominaOutputType rendir(cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RindeNominaInputType rindeNominaInput) throws 
        cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.ErrorType,  java.rmi.RemoteException;
    public void generarArchivo(cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CargaNominaInputType cargaNominaInput) throws 
         java.rmi.RemoteException;
}
