// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.services.ws.proxy;

import javax.xml.rpc.*;

public interface EnvioNominasPortService extends javax.xml.rpc.Service {
    public cl.bicevida.envionominas.model.services.ws.proxy.EnvioNominasPort get__soap_EnvioNominas_RS_envioNominasPort() throws javax.xml.rpc.ServiceException;
}
