// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.proxy.bdclientes.consultas.runtime;

import oracle.j2ee.ws.client.BasicService;
import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.common.encoding.simpletype.*;
import oracle.j2ee.ws.common.encoding.soap.*;
import oracle.j2ee.ws.common.encoding.literal.*;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.common.soap.SOAPEncodingConstants;
import oracle.j2ee.ws.common.wsdl.document.schema.SchemaConstants;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.namespace.QName;

public class WSClientesConsultaFaseTres_Service_SerializerRegistry extends SerializerRegistryBase implements SerializerConstants {
    public WSClientesConsultaFaseTres_Service_SerializerRegistry() {
    }
    
    public TypeMappingRegistry getRegistry() {
        TypeMappingRegistry registry = BasicService.createStandardTypeMappingRegistry();
        TypeMapping mapping11 = registry.getTypeMapping(SOAPEncodingConstants.getSOAPEncodingConstants(SOAPVersion.SOAP_11).getURIEncoding());
        TypeMapping mapping = registry.getTypeMapping("");
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "consultaContratoCanalRemotoElement");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.ConsultaContratoCanalRemotoElement_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ConsultaContratoCanalRemotoElement.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "EstadoCivilModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.EstadoCivilModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.EstadoCivilModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "consultaPersonaElement");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.ConsultaPersonaElement_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ConsultaPersonaElement.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "consultaDireccionResponseElement");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.ConsultaDireccionResponseElement_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ConsultaDireccionResponseElement.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "PersonaModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.PersonaModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.PersonaModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "IsapreModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.IsapreModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.IsapreModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "RetPersona");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.RetPersona_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.RetPersona.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "NivelEducacionalModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.NivelEducacionalModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.NivelEducacionalModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "TipoCalleModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.TipoCalleModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.TipoCalleModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "TipoPersonaModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.TipoPersonaModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.TipoPersonaModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "TipoViviendaModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.TipoViviendaModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.TipoViviendaModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "ActividadModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.ActividadModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ActividadModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "consultaPersonaResponseElement");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.ConsultaPersonaResponseElement_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ConsultaPersonaResponseElement.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "consultaDireccionElement");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.ConsultaDireccionElement_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ConsultaDireccionElement.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "RegionModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.RegionModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.RegionModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "AFPModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.AFPModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.AFPModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "CodigoAreaModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.CodigoAreaModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.CodigoAreaModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "ProfesionModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.ProfesionModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ProfesionModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "ProvinciaModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.ProvinciaModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ProvinciaModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "TipoLocalidadModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.TipoLocalidadModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.TipoLocalidadModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "RetDireccion");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.RetDireccion_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.RetDireccion.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "RetConsultaContratoCanalRemoto");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.RetConsultaContratoCanalRemoto_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.RetConsultaContratoCanalRemoto.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "GSEModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.GSEModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.GSEModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "SexoModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.SexoModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.SexoModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "NivelIngresoModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.NivelIngresoModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.NivelIngresoModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "OcupacionModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.OcupacionModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.OcupacionModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "NacionalidadModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.NacionalidadModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.NacionalidadModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "DireccionModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.DireccionModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.DireccionModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "TipoDireccionModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.TipoDireccionModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.TipoDireccionModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "ComunaModel");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.ComunaModel_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ComunaModel.class, type, serializer);
        }
        {
            QName type = new QName("http://consulta.ws.fasetres.actualizadatos.bicevida.cl/types/", "consultaContratoCanalRemotoResponseElement");
            CombinedSerializer serializer = new cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.runtime.ConsultaContratoCanalRemotoResponseElement_LiteralSerializer(type, DONT_ENCODE_TYPE);
            registerSerializer(mapping,cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.consulta.types.ConsultaContratoCanalRemotoResponseElement.class, type, serializer);
        }
        cl.bicevida.core.model.services.ws.proxy.bdclientes.consultas.runtime.WSClientesConsultaFaseTres_Service_SerializerRegistry12 internal12Registry = new cl.bicevida.core.model.services.ws.proxy.bdclientes.consultas.runtime.WSClientesConsultaFaseTres_Service_SerializerRegistry12();
        return internal12Registry.getRegistry(registry);
    }
    
    private static void registerSerializer(TypeMapping mapping, Class javaType, QName xmlType,
        Serializer ser) {
        mapping.register(javaType, xmlType, new SingletonSerializerFactory(ser),
            new SingletonDeserializerFactory((Deserializer)ser));
    }
    
}
