// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.proxy.oid.runtime;


public class OidBasicWebServiceSoapHttp_createUser_ReqS implements java.io.Serializable {
    protected java.lang.String uid;
    protected java.lang.String cn;
    protected java.lang.String sn;
    protected java.lang.String mail;
    protected java.lang.String givenname;
    protected java.lang.String fechanacimiento;
    protected java.lang.String accountname;
    protected java.lang.String userpassword;
    protected java.lang.String telefono;
    
    public OidBasicWebServiceSoapHttp_createUser_ReqS() {
    }
    
    public java.lang.String getUid() {
        return uid;
    }
    
    public void setUid(java.lang.String uid) {
        this.uid = uid;
    }
    
    public java.lang.String getCn() {
        return cn;
    }
    
    public void setCn(java.lang.String cn) {
        this.cn = cn;
    }
    
    public java.lang.String getSn() {
        return sn;
    }
    
    public void setSn(java.lang.String sn) {
        this.sn = sn;
    }
    
    public java.lang.String getMail() {
        return mail;
    }
    
    public void setMail(java.lang.String mail) {
        this.mail = mail;
    }
    
    public java.lang.String getGivenname() {
        return givenname;
    }
    
    public void setGivenname(java.lang.String givenname) {
        this.givenname = givenname;
    }
    
    public java.lang.String getFechanacimiento() {
        return fechanacimiento;
    }
    
    public void setFechanacimiento(java.lang.String fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    
    public java.lang.String getAccountname() {
        return accountname;
    }
    
    public void setAccountname(java.lang.String accountname) {
        this.accountname = accountname;
    }
    
    public java.lang.String getUserpassword() {
        return userpassword;
    }
    
    public void setUserpassword(java.lang.String userpassword) {
        this.userpassword = userpassword;
    }
    
    public java.lang.String getTelefono() {
        return telefono;
    }
    
    public void setTelefono(java.lang.String telefono) {
        this.telefono = telefono;
    }
}
