// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.proxy.oid.runtime;


public class OidBasicWebServiceSoapHttp_createGroup_ReqS implements java.io.Serializable {
    protected java.lang.String groupName;
    protected java.lang.String description;
    
    public OidBasicWebServiceSoapHttp_createGroup_ReqS() {
    }
    
    public java.lang.String getGroupName() {
        return groupName;
    }
    
    public void setGroupName(java.lang.String groupName) {
        this.groupName = groupName;
    }
    
    public java.lang.String getDescription() {
        return description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
}
