<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="EnvioNominas_ArchivoNominas_BCI_RS.wsdl"/>
      <rootElement name="cargaPeticion" namespace="http://bci.ws/infraestructuradenegocios/nominas/nominasbel"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="ArchivosNomina_BD.wsdl"/>
      <rootElement name="EvnmArchivosNominasCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ArchivosNominaBD"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.5.0(build 090730.0200.1754) AT [WED NOV 30 15:27:09 GMT-04:00 2011]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:ns1="http://bci.ws/infraestructuradenegocios/nominas/nominasbel"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns2="http://bci.ws/infraestructuradenegocios/nominas/nominasbel/types/rut"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ArchivosNominaBD"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:serv="http://bci.ws/infraestructuradenegocios/nominas/nominasbel/types"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ArchivosNomina_BD/"
                xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/db/"
                exclude-result-prefixes="xsl ns1 wsdl ns2 ns0 soap serv plt pc jca top tns hdr bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <top:EvnmArchivosNominasCollection>
      <top:EvnmArchivosNominas>
        <top:nombreArchivo>
          <xsl:value-of select="/ns1:cargaPeticion/serv:archivo/serv:nombre"/>
        </top:nombreArchivo>
        <top:referenciaBancoProceso>
          <xsl:text disable-output-escaping="no">32</xsl:text>
        </top:referenciaBancoProceso> 
        <top:fechaCreacion>
          <xsl:value-of select="xp20:current-dateTime()"/>
        </top:fechaCreacion>
        <top:cuerpo>
          <xsl:value-of select="/ns1:cargaPeticion/serv:archivo/serv:cuerpo"/>
        </top:cuerpo>
      </top:EvnmArchivosNominas>
    </top:EvnmArchivosNominasCollection>
  </xsl:template>
</xsl:stylesheet>
