<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="nominasbel.wsdl"/>
      <rootElement name="cargaRespuesta" namespace="http://bci.ws/infraestructuradenegocios/nominas/nominasbel"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="EnvioNominas.xsd"/>
      <rootElement name="CargaNominaOutput" namespace="http://bicevida.ws/services/envionominas"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.5.0(build 090730.0200.1754) AT [MON FEB 21 16:53:36 CLST 2011]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:tns="http://bci.ws/infraestructuradenegocios/nominas/nominasbel"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns1="http://bci.ws/infraestructuradenegocios/nominas/nominasbel/types/rut"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:serv="http://bci.ws/infraestructuradenegocios/nominas/nominasbel/types"
                xmlns:ns0="http://bicevida.ws/services/envionominas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                exclude-result-prefixes="xsl tns wsdl ns1 xsd soap serv ns0 bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <ns0:CargaNominaOutput>
      <ns0:respuestaServicio>
        <xsl:value-of select="xp20:compare(/tns:cargaRespuesta/serv:codigoRespuesta,'0')"/>
      </ns0:respuestaServicio>
    </ns0:CargaNominaOutput>
  </xsl:template>
</xsl:stylesheet>
