<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="ArchivoRendicionBICE.wsdl"/>
      <rootElement name="Nomina" namespace="http://TargetNamespace.com/ArchivoRendicionBICE"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="EnvioNominas_BICE_RENDICION_OUT.wsdl"/>
      <rootElement name="RindeNominaOutput" namespace="http://bicevida.ws/services/envionominas"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.5.0(build 090730.0200.1754) AT [THU DEC 01 18:04:07 GMT-04:00 2011]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:imp1="http://TargetNamespace.com/ArchivoRendicionBICE"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/EnvioNominas_BICE_RENDICION_OUT/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/ArchivoRendicionBICE/"
                xmlns:ns2="http://bicevida.ws/services/envionominas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/file/"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/jms/"
                exclude-result-prefixes="xsl imp1 plt pc jca ns0 tns hdr ns1 ns2 ns3 bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <ns2:RindeNominaOutput>
      <ns2:respuestaServicio>
        <xsl:value-of select="/imp1:Nomina/imp1:TransaccionPago/imp1:NOM_ARCHIVO"/>
      </ns2:respuestaServicio>
      <ns2:nominas>
        <ns2:nomina>
          <ns2:registrosNomina>
            <xsl:for-each select="/imp1:Nomina/imp1:TransaccionPago">
              <ns2:registro>
                <ns2:rut>
                  <xsl:value-of select="substring(imp1:RUT_TITULAR,6.0,2.0)"/>
                </ns2:rut>
                <ns2:digitoVerificador>
                  <xsl:value-of select="imp1:RUT_TITULAR"/>
                </ns2:digitoVerificador>
                <ns2:nombre>
                  <xsl:value-of select="imp1:NOM_TITULAR"/>
                </ns2:nombre>
                <ns2:banco>
                  <xsl:value-of select="imp1:COD_BANCO"/>
                </ns2:banco>
                <ns2:cuenta>
                  <xsl:value-of select="imp1:NUM_CTATIT"/>
                </ns2:cuenta>
                <ns2:monto>
                  <xsl:value-of select="imp1:MTO_MONTO"/>
                </ns2:monto>
                <ns2:fechaMovimiento>
                  <xsl:value-of select="imp1:FEC_FECHA"/>
                </ns2:fechaMovimiento>
                <ns2:glosa>
                  <xsl:value-of select="imp1:GLS_GLOSA"/>
                </ns2:glosa>
                <ns2:estadoPago>
                  <xsl:value-of select="imp1:COD_ESTADO_REN"/>
                </ns2:estadoPago>
                <ns2:tipoCuenta>
                  <xsl:value-of select="imp1:COD_TIPCTA"/>
                </ns2:tipoCuenta>
              </ns2:registro>
            </xsl:for-each>
          </ns2:registrosNomina>
        </ns2:nomina>
      </ns2:nominas>
    </ns2:RindeNominaOutput>
  </xsl:template>
</xsl:stylesheet>
