// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas;


public class CamposVariables implements java.io.Serializable {
    protected cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CampoVariableType[] campoVariable;
    
    public CamposVariables() {
    }
    
    public cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CampoVariableType[] getCampoVariable() {
        return campoVariable;
    }
    
    public void setCampoVariable(cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CampoVariableType[] campoVariable) {
        this.campoVariable = campoVariable;
    }
}
