// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas;


public class CampoVariableType implements java.io.Serializable {
    protected java.lang.String nombre;
    protected java.lang.String valor;
    
    public CampoVariableType() {
    }
    
    public java.lang.String getNombre() {
        return nombre;
    }
    
    public void setNombre(java.lang.String nombre) {
        this.nombre = nombre;
    }
    
    public java.lang.String getValor() {
        return valor;
    }
    
    public void setValor(java.lang.String valor) {
        this.valor = valor;
    }
}
