// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas;


public class RegistrosNomina implements java.io.Serializable {
    protected cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RegistroNominaType[] registro;
    
    public RegistrosNomina() {
    }
    
    public cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RegistroNominaType[] getRegistro() {
        return registro;
    }
    
    public void setRegistro(cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.RegistroNominaType[] registro) {
        this.registro = registro;
    }
}
