// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.proxy.oid.runtime;


public class OidBasicWebServiceSoapHttp_findGroupsDN_ReqS implements java.io.Serializable {
    
    public OidBasicWebServiceSoapHttp_findGroupsDN_ReqS() {
    }
}
