// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.proxy.oid.runtime;


public class OidBasicWebServiceSoapHttp_intelliActualizarUsuario_ReqS implements java.io.Serializable {
    protected java.lang.String pRut;
    protected java.lang.String pNombres;
    protected java.lang.String pApellidos;
    protected java.lang.String pMail;
    protected java.lang.String pFechaNacimiento;
    protected java.lang.String pUserPassword;
    protected java.lang.String pTelefono;
    protected java.lang.String[] pGroups;
    
    public OidBasicWebServiceSoapHttp_intelliActualizarUsuario_ReqS() {
    }
    
    public java.lang.String getPRut() {
        return pRut;
    }
    
    public void setPRut(java.lang.String pRut) {
        this.pRut = pRut;
    }
    
    public java.lang.String getPNombres() {
        return pNombres;
    }
    
    public void setPNombres(java.lang.String pNombres) {
        this.pNombres = pNombres;
    }
    
    public java.lang.String getPApellidos() {
        return pApellidos;
    }
    
    public void setPApellidos(java.lang.String pApellidos) {
        this.pApellidos = pApellidos;
    }
    
    public java.lang.String getPMail() {
        return pMail;
    }
    
    public void setPMail(java.lang.String pMail) {
        this.pMail = pMail;
    }
    
    public java.lang.String getPFechaNacimiento() {
        return pFechaNacimiento;
    }
    
    public void setPFechaNacimiento(java.lang.String pFechaNacimiento) {
        this.pFechaNacimiento = pFechaNacimiento;
    }
    
    public java.lang.String getPUserPassword() {
        return pUserPassword;
    }
    
    public void setPUserPassword(java.lang.String pUserPassword) {
        this.pUserPassword = pUserPassword;
    }
    
    public java.lang.String getPTelefono() {
        return pTelefono;
    }
    
    public void setPTelefono(java.lang.String pTelefono) {
        this.pTelefono = pTelefono;
    }
    
    public java.lang.String[] getPGroups() {
        return pGroups;
    }
    
    public void setPGroups(java.lang.String[] pGroups) {
        this.pGroups = pGroups;
    }
}
