// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.proxy.oid.runtime;


public class OidBasicWebServiceSoapHttp_deleteUsersFromGroup_RespS implements java.io.Serializable {
    protected boolean result;
    
    public OidBasicWebServiceSoapHttp_deleteUsersFromGroup_RespS() {
    }
    
    public boolean isResult() {
        return result;
    }
    
    public void setResult(boolean result) {
        this.result = result;
    }
}
