// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.proxy.oid.runtime;


public class OidBasicWebServiceSoapHttp_modifyUserProperty_ReqS implements java.io.Serializable {
    protected java.lang.String user;
    protected java.lang.String propertyName;
    protected java.lang.String[] values;
    
    public OidBasicWebServiceSoapHttp_modifyUserProperty_ReqS() {
    }
    
    public java.lang.String getUser() {
        return user;
    }
    
    public void setUser(java.lang.String user) {
        this.user = user;
    }
    
    public java.lang.String getPropertyName() {
        return propertyName;
    }
    
    public void setPropertyName(java.lang.String propertyName) {
        this.propertyName = propertyName;
    }
    
    public java.lang.String[] getValues() {
        return values;
    }
    
    public void setValues(java.lang.String[] values) {
        this.values = values;
    }
}
