// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.proxy.oid.runtime;


public class OidBasicWebServiceSoapHttp_validateUserPassword_ReqS implements java.io.Serializable {
    protected java.lang.String cn;
    protected java.lang.String password;
    
    public OidBasicWebServiceSoapHttp_validateUserPassword_ReqS() {
    }
    
    public java.lang.String getCn() {
        return cn;
    }
    
    public void setCn(java.lang.String cn) {
        this.cn = cn;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
}
