// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.proxy.oid.runtime;


public class OidBasicWebServiceSoapHttp_createUser2_ReqS implements java.io.Serializable {
    protected java.lang.String[] propertyNames;
    protected java.lang.String[] propertyValues;
    
    public OidBasicWebServiceSoapHttp_createUser2_ReqS() {
    }
    
    public java.lang.String[] getPropertyNames() {
        return propertyNames;
    }
    
    public void setPropertyNames(java.lang.String[] propertyNames) {
        this.propertyNames = propertyNames;
    }
    
    public java.lang.String[] getPropertyValues() {
        return propertyValues;
    }
    
    public void setPropertyValues(java.lang.String[] propertyValues) {
        this.propertyValues = propertyValues;
    }
}
