<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="nominasbel.wsdl"/>
      <rootElement name="cargaPeticion" namespace="http://bci.ws/infraestructuradenegocios/nominas/nominasbel"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="ArchivoNominas.wsdl"/>
      <rootElement name="ArchivoNominaOutput" namespace="http://bicevida.ws/services/envionominas"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.5.0(build 090730.0200.1754) AT [TUE MAR 08 00:51:49 CLST 2011]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:tns="http://bci.ws/infraestructuradenegocios/nominas/nominasbel"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns0="http://bci.ws/infraestructuradenegocios/nominas/nominasbel/types/rut"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/file/ArchivoNominas/"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:serv="http://bci.ws/infraestructuradenegocios/nominas/nominasbel/types"
                xmlns:imp1="http://bicevida.ws/services/envionominas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/file/"
                exclude-result-prefixes="xsl tns wsdl ns0 xsd soap serv plt jca ns1 imp1 hdr bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <imp1:ArchivoNominaOutput>
      <imp1:idBancoProceso>
        <xsl:text disable-output-escaping="no">32</xsl:text>
      </imp1:idBancoProceso>
      <imp1:nombre>
        <xsl:value-of select="/tns:cargaPeticion/serv:archivo/serv:nombre"/>
      </imp1:nombre>
      <imp1:cuerpo>
        <xsl:value-of select="/tns:cargaPeticion/serv:archivo/serv:cuerpo"/>
      </imp1:cuerpo>
    </imp1:ArchivoNominaOutput>
  </xsl:template>
</xsl:stylesheet>
