<?xml version='1.0' encoding='utf-8' ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="EnvioNominas.xsd"/>
      <rootElement name="RindeNominaInput" namespace="http://bicevida.ws/services/envionominas"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="nominasbel.wsdl"/>
      <rootElement name="rendicionPeticion" namespace="http://bci.ws/infraestructuradenegocios/nominas/nominasbel"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.5.0(build 090730.0200.1754) AT [TUE FEB 22 18:18:02 CLST 2011]. -->
?>
<xsl:stylesheet version="1.0" xmlns:tns="http://bci.ws/infraestructuradenegocios/nominas/nominasbel" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:ns1="http://bci.ws/infraestructuradenegocios/nominas/nominasbel/types/rut" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:serv="http://bci.ws/infraestructuradenegocios/nominas/nominasbel/types" xmlns:ns0="http://bicevida.ws/services/envionominas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" exclude-result-prefixes="xsl xsd ns0 tns wsdl ns1 soap serv bpws ehdr hwf xp20 xref ora ids orcl"
                xmlns:env="http://bicevida.ws/services/envionominas" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
	<xsl:template match="/">
		<tns:rendicionPeticion>
			<serv:rutEmpresa>
				<ns1:rut>
					<xsl:for-each select="env:RindeNominaInput/env:datosCabecera/env:camposVariables/env:campoVariable">
						<xsl:if test="env:nombre = 'rutEmpresa'">
							<xsl:value-of select="env:valor"/>
						</xsl:if>
					</xsl:for-each>
				</ns1:rut>
				<ns1:digitoVerificador>
					<xsl:for-each select="env:RindeNominaInput/env:datosCabecera/env:camposVariables/env:campoVariable">
						<xsl:if test="env:nombre = 'dvRutEmpresa'">
							<xsl:value-of select="env:valor"/>
						</xsl:if>
					</xsl:for-each>
				</ns1:digitoVerificador>
			</serv:rutEmpresa>
			<serv:rutUsuario>
				<ns1:rut>
					<xsl:for-each select="env:RindeNominaInput/env:datosCabecera/env:camposVariables/env:campoVariable">
						<xsl:if test="env:nombre = 'rutUsuario'">
							<xsl:value-of select="env:valor"/>
						</xsl:if>
					</xsl:for-each>
				</ns1:rut>
				<ns1:digitoVerificador>
					<xsl:for-each select="env:RindeNominaInput/env:datosCabecera/env:camposVariables/env:campoVariable">
						<xsl:if test="env:nombre = 'dvRutUsuario'">
							<xsl:value-of select="env:valor"/>
						</xsl:if>
					</xsl:for-each>
				</ns1:digitoVerificador>
			</serv:rutUsuario>
			<serv:convenio>
				<xsl:for-each select="env:RindeNominaInput/env:datosCabecera/env:camposVariables/env:campoVariable">
					<xsl:if test="env:nombre = 'convenio'">
						<xsl:value-of select="env:valor"/>
					</xsl:if>
				</xsl:for-each>
			</serv:convenio>
			<serv:canal>
				<xsl:for-each select="env:RindeNominaInput/env:datosCabecera/env:camposVariables/env:campoVariable">
					<xsl:if test="env:nombre = 'canal'">
						<xsl:value-of select="env:valor"/>
					</xsl:if>
				</xsl:for-each>
			</serv:canal>
			<serv:pin>
				<xsl:for-each select="env:RindeNominaInput/env:datosCabecera/env:camposVariables/env:campoVariable">
					<xsl:if test="env:nombre = 'pin'">
						<xsl:value-of select="env:valor"/>
					</xsl:if>
				</xsl:for-each>
			</serv:pin>
			<serv:servicio>
				<xsl:for-each select="env:RindeNominaInput/env:datosCabecera/env:camposVariables/env:campoVariable">
					<xsl:if test="env:nombre = 'servicio'">
						<xsl:value-of select="env:valor"/>
					</xsl:if>
				</xsl:for-each>
			</serv:servicio>
			<xsl:if test="env:RindeNominaInput/env:tipoRendicion = 'PAGO'">
				<serv:tipo>
					<xsl:for-each select="env:RindeNominaInput/env:datosCabecera/env:camposVariables/env:campoVariable">
						<xsl:if test="env:nombre = 'tipoRendicionPago'">
							<xsl:value-of select="env:valor"/>
						</xsl:if>
					</xsl:for-each>
				</serv:tipo>
			</xsl:if>
			<xsl:if test="env:RindeNominaInput/env:tipoRendicion = 'CARGA'">
				<serv:tipo>
					<xsl:for-each select="env:RindeNominaInput/env:datosCabecera/env:camposVariables/env:campoVariable">
						<xsl:if test="env:nombre = 'tipoRendicionCarga'">
							<xsl:value-of select="env:valor"/>
						</xsl:if>
					</xsl:for-each>
				</serv:tipo>
			</xsl:if>
			<serv:formato>
				<xsl:for-each select="env:RindeNominaInput/env:datosCabecera/env:camposVariables/env:campoVariable">
					<xsl:if test="env:nombre = 'formato'">
						<xsl:value-of select="env:valor"/>
					</xsl:if>
				</xsl:for-each>
			</serv:formato>
			<serv:fecha>
				<xsl:value-of select="concat(substring(env:RindeNominaInput/env:fecha,9,2),substring(env:RindeNominaInput/env:fecha,6,2),substring(env:RindeNominaInput/env:fecha,1,4))"/>
			</serv:fecha>
		</tns:rendicionPeticion>
	</xsl:template>
</xsl:stylesheet>