// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas;


public class ArchivoNominaType implements java.io.Serializable {
    protected java.lang.String idBancoProceso;
    protected java.lang.String nombre;
    protected java.lang.String cuerpo;
    
    public ArchivoNominaType() {
    }
    
    public java.lang.String getIdBancoProceso() {
        return idBancoProceso;
    }
    
    public void setIdBancoProceso(java.lang.String idBancoProceso) {
        this.idBancoProceso = idBancoProceso;
    }
    
    public java.lang.String getNombre() {
        return nombre;
    }
    
    public void setNombre(java.lang.String nombre) {
        this.nombre = nombre;
    }
    
    public java.lang.String getCuerpo() {
        return cuerpo;
    }
    
    public void setCuerpo(java.lang.String cuerpo) {
        this.cuerpo = cuerpo;
    }
}
