// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas;


public class CargaNominaOutputType implements java.io.Serializable {
    protected java.lang.String respuestaServicio;
    
    public CargaNominaOutputType() {
    }
    
    public java.lang.String getRespuestaServicio() {
        return respuestaServicio;
    }
    
    public void setRespuestaServicio(java.lang.String respuestaServicio) {
        this.respuestaServicio = respuestaServicio;
    }
}
