// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas;


public class DatosCabeceraType implements java.io.Serializable {
    protected java.lang.String bancoProceso;
    protected java.util.Calendar fechaActual;
    protected cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CamposVariables camposVariables;
    
    public DatosCabeceraType() {
    }
    
    public java.lang.String getBancoProceso() {
        return bancoProceso;
    }
    
    public void setBancoProceso(java.lang.String bancoProceso) {
        this.bancoProceso = bancoProceso;
    }
    
    public java.util.Calendar getFechaActual() {
        return fechaActual;
    }
    
    public void setFechaActual(java.util.Calendar fechaActual) {
        this.fechaActual = fechaActual;
    }
    
    public cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CamposVariables getCamposVariables() {
        return camposVariables;
    }
    
    public void setCamposVariables(cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.CamposVariables camposVariables) {
        this.camposVariables = camposVariables;
    }
}
