// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.5.0, build 090727.2000.36696)

package cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas;

import cl.bicevida.envionominas.model.bo.transaccionPago;


public class RindeNominaOutputType implements java.io.Serializable {
    protected java.lang.String respuestaServicio;
    protected cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.Nominas nominas;
    protected cl.bicevida.envionominas.model.bo.transaccionPago[] transaccionPago;

    public void setTransaccionPago(transaccionPago[] transaccionPago) {
        this.transaccionPago = transaccionPago;
    }

    public transaccionPago[] getTransaccionPago() {
        return transaccionPago;
    }
    
    public RindeNominaOutputType() {
    }
    
    public java.lang.String getRespuestaServicio() {
        return respuestaServicio;
    }
    
    public void setRespuestaServicio(java.lang.String respuestaServicio) {
        this.respuestaServicio = respuestaServicio;
    }
    
    public cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.Nominas getNominas() {
        return nominas;
    }
    
    public void setNominas(cl.bicevida.envionominas.model.types.ws.bicevida.services.envionominas.Nominas nominas) {
        this.nominas = nominas;
    }
}
