// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types;


public class GetListaSexoResponseElement implements java.io.Serializable {
    protected cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaSexo result;
    
    public GetListaSexoResponseElement() {
    }
    
    public cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaSexo getResult() {
        return result;
    }
    
    public void setResult(cl.bicevida.core.model.services.ws.types.actualizadatos.fasetres.ws.param.types.RetListaSexo result) {
        this.result = result;
    }
}
