// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package cl.bicevida.core.model.services.ws.proxy.bdclientes.parametros.runtime;

import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.client.ServiceExceptionImpl;
import oracle.j2ee.ws.common.util.exception.*;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.rpc.handler.HandlerChain;
import javax.xml.rpc.handler.HandlerInfo;
import javax.xml.namespace.QName;

public class WSClientesParamFaseTres_Service_Impl extends oracle.j2ee.ws.client.BasicService implements cl.bicevida.core.model.services.ws.proxy.bdclientes.parametros.WSClientesParamFaseTres_Service {
    private static final QName serviceName = new QName("http://param.ws.fasetres.actualizadatos.bicevida.cl/", "WSClientesParamFaseTres");
    private static final QName ns1_WSClientesParamFaseTresSoapHttpPort_QNAME = new QName("http://param.ws.fasetres.actualizadatos.bicevida.cl/", "WSClientesParamFaseTresSoapHttpPort");
    private static final Class WSClientesParamFaseTres_PortType_PortClass = cl.bicevida.core.model.services.ws.proxy.bdclientes.parametros.WSClientesParamFaseTres_PortType.class;
    
    public WSClientesParamFaseTres_Service_Impl() {
        super(serviceName, new QName[] {
                        ns1_WSClientesParamFaseTresSoapHttpPort_QNAME
                    },
            new cl.bicevida.core.model.services.ws.proxy.bdclientes.parametros.runtime.WSClientesParamFaseTres_Service_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(QName portName, Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_WSClientesParamFaseTresSoapHttpPort_QNAME) &&
                serviceDefInterface.equals(WSClientesParamFaseTres_PortType_PortClass)) {
                return getWSClientesParamFaseTresSoapHttpPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(WSClientesParamFaseTres_PortType_PortClass)) {
                return getWSClientesParamFaseTresSoapHttpPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public cl.bicevida.core.model.services.ws.proxy.bdclientes.parametros.WSClientesParamFaseTres_PortType getWSClientesParamFaseTresSoapHttpPort() {
        String[] roles = new String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_WSClientesParamFaseTresSoapHttpPort_QNAME));
        handlerChain.setRoles(roles);
        cl.bicevida.core.model.services.ws.proxy.bdclientes.parametros.runtime.WSClientesParamFaseTresSoapHttp_Stub stub = new cl.bicevida.core.model.services.ws.proxy.bdclientes.parametros.runtime.WSClientesParamFaseTresSoapHttp_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
